### ISSUE TITLE
BUG : crash server on vision calculation

### ISSUE THREAD

**Issue by thyshimrod** [azziliz/MurmuresJS#58]
C:\pascal\MurmuresJS\src\character.js:52
          level.tiles[Math.floor(oy)][Math.floor(ox)].state = 1;
                                                            ^

TypeError: Cannot set property 'state' of undefined
    at character.setVision (C:\pascal\MurmuresJS\src\character.js:52:61)
    at gameEngine.applyOrder (C:\pascal\MurmuresJS\src\gameEngine.js:89:23)
    at IncomingMessage.<anonymous> (C:\pascal\MurmuresJS\server.js:91:36)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by azziliz** [comment]
reproduced everytime on cell (3,7) in level3 (movement 9 then 9 then 8 from start point)
